

all:
	g++ -O0 -g -ggdb -Wall -lpthread -o ./bin/fast_test fast_test.cpp ../log4z.cpp 
	g++ -O0 -g -ggdb -Wall -lpthread -o ./bin/advanced_test advanced_test.cpp ../log4z.cpp 
	g++ -O0 -g -ggdb -Wall -lpthread -o ./bin/stress_test stress_test.cpp ../log4z.cpp 
clean:	
	rm -f ./bin/fast_test ./bin/advanced_test ./bin/stress_test *.o


