

all:
	g++ -g -ggdb -Wall -lpthread -o fast_test fast_test.cpp ../log4z.cpp 
	g++ -g -ggdb -Wall -lpthread -o advanced_test advanced_test.cpp ../log4z.cpp 
	g++ -g -ggdb -Wall -lpthread -o stress_test stress_test.cpp ../log4z.cpp 
clean:	
	rm -f fast_test advanced_test stress_test *.o


